[package]
name = "chord_midi_web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { version = "0.21", features = ["csr"] }
web-sys = "0.3.66"
chord_midi = { path = "../chord_midi" }
